name: Build Swiftfin

on:
  push:
    branches:
      - build-workflow

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies -scheme Swiftfin SWIFT_MACROS_ENABLED=YES

      - name: Build for Simulator
        run: |
          xcodebuild -scheme Swiftfin -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 16' -derivedDataPath build CODE_SIGNING_ALLOWED=YES CODE_SIGNING_REQUIRED=NO BUILD_ACTIVE_ARCH_ONLY=NO SWIFT_MACROS_ENABLED=YES -sdk iphonesimulator build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Swiftfin-App
          path: build/Build/Products/Debug-iphonesimulator/Swiftfin.app
